[package]
name = "fire"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }

[dev-dependencies]
proptest = "1"
